### Aula 17_04_2021

#### Repetições FOR

In [2]:
frutas=['abacate','pera','abacaxi']

In [8]:
for elemento in frutas:
    print(frutas)

['abacate', 'pera', 'abacaxi']
['abacate', 'pera', 'abacaxi']
['abacate', 'pera', 'abacaxi']


In [14]:
frutas=['abacate','pera','abacaxi']

In [16]:
for frutas in frutas:
    if frutas.startswith('a'):
        print(frutas)

abacate
abacaxi


In [18]:
list_num=[1,2,3,4,5]
soma=0
for numero in list_num:
    soma = soma + numero
    print(soma)

1
3
6
10
15


#### Exercício slide 48

In [1]:
Lista_multiplos=[1,2,3,4,5,6,7,8,9,10]

In [2]:
type(Lista_multiplos)

list

In [4]:
number=int(input('Insira um número inteiro entre 0 e 10: '))

Insira um número inteiro entre 0 e 10: 8


In [6]:
#Faça um laço for que imprima os valores da tabuada de number.
Lista_multiplos=[1,2,3,4,5,6,7,8,9,10]

number=int(input('Insira um número inteiro entre 0 e 10: '))

for numero in Lista_multiplos:
    print(number*numero)

Insira um número inteiro entre 0 e 10: 7
7
14
21
28
35
42
49
56
63
70


#### Loops While

In [7]:
condicao=1
soma=0

while condicao <= 5:
    soma = soma + condicao 
    condicao = condicao + 1
    print(soma)

1
3
6
10
15


In [ ]:
#contador=1 / 
#enquanto contador <=10 / 
#imprima (contador) / 
#contador = contador + 2/ 
#se (contador ==5) / 
#contador=contador+2

In [4]:
contador = 1

while contador <= 10:
    print(contador)
    contador = contador + 2
    
    if contador == 5:
        contador = contador + 2  

1
3
7
9


______________________
#### Exercício slide 51 ## ???

In [8]:
#Peça um número inteiro entre 2 e 15 ao usuário e atribua na variável valor.
valor= int(input('Escolha um número inteiro entre 0 e 15: '))

Escolha um número inteiro entre 0 e 15: 13


In [ ]:
#Crie uma variável fat e atribua um valor inicial igual a zero.

In [ ]:
#Crie um contador cont e atribua um valor inicial igual a zero.

In [ ]:
#Usando um loop while, enquanto cont for menor que valor, atualize fat  como fat = fat x valor
#Quando o loop terminar, imprima “O fatorial de <valor> é <fat>”, em que
#<valor> é o número dado pelo usuário e <fat> seja o resultado do loop.

In [ ]:
fat = 1 
cont = 0

while cont < valor 
    fat = fat + valor 
    cont = cont + 1
    
print('O Fatorial de %d é %d' (%valor,fat))

## Numpy

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
idades = pd.Series([15,21,30,12], index=['João', 'Maria', 'Ana', 'Pedro'])

In [4]:
idades

João     15
Maria    21
Ana      30
Pedro    12
dtype: int64

In [5]:
idades.index

Index(['João', 'Maria', 'Ana', 'Pedro'], dtype='object')

In [8]:
idades.values

array([15, 21, 30, 12], dtype=int64)

In [9]:
np.array([1,2,3])

array([1, 2, 3])

In [11]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [16]:
one = np.ones([2,2])
one

array([[1., 1.],
       [1., 1.]])

In [17]:
zeros = np.zeros([2,2,2])
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [34]:
vet = np.array([[1,2,3],[4,5,6],[7,8,9]])
vet

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
vet.shape

(3, 3)

In [36]:
vet[1,:]

array([4, 5, 6])

In [37]:
vet[:,2]

array([3, 6, 9])

In [38]:
vet[1,1]

5

In [32]:
arr=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
arr

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [33]:
arr.shape

(2, 2, 2)

In [39]:
arr[0,0,1]

2

In [41]:
arr[1,1,0]

3

In [42]:
data = np.arange(10)

In [43]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

____________
### Dataframe

In [17]:
df = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]), columns=['a','b','c'])

In [18]:
df

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [16]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
dados = {
    'nome' : ['Bill', 'Fill', 'Steve', 'Bob', 'Karina', 'João', 'José'], 
    'idade' : [21, 87, 56, 43, 28, 30, 35]
}

In [20]:
dados

{'nome': ['Bill', 'Fill', 'Steve', 'Bob', 'Karina', 'João', 'José'],
 'idade': [21, 87, 56, 43, 28, 30, 35]}

In [21]:
type(dados)

dict

In [24]:
df= pd.DataFrame(dados, index=['a','b','c','d','e','f','g'])

In [25]:
df

nome  idade
a    Bill     21
b    Fill     87
c   Steve     56
d     Bob     43
e  Karina     28
f    João     30
g    José     35

In [26]:
df.shape

(7, 2)

In [27]:
df.columns

Index(['nome', 'idade'], dtype='object')

In [28]:
df = pd.read_excel('bank-full.xlsx', sheet_name='Sheet 1 - bank-full')

In [29]:
df

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome  
0        unknown    5   may       261         1     -1         0  unknown  
1        unknown    5   may       151         1     -1         0  unknown  
2        unknown    5   may        76         1     -1         0  unknown  
3        unknown    5   may        92         1     -1         0  unknown  
4        unknown    5   may       198         1     -1         0  unknown  
...          ...  ...   ...       ...       ...    ...       ...      ...  
45206   cellular   17   nov       977         3     -1         0  unknown  
45207   cellular   17   nov       456         2     -1         0  unknown  
45208   cellular   17   nov      1127         5    184         3  success  
45209  telephone   17   nov       508         4     -1         0  unknown  
45210   cellular   17   nov       361         2    188        11    other  

[45211 rows x 16 columns]

In [30]:
df.shape

(45211, 16)

In [31]:
type(df)

pandas.core.frame.DataFrame

In [35]:
#10primeiras linhas
df.head(10)

age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married    unknown      no     1506     yes   no   
4   33       unknown    single    unknown      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome  
0  unknown    5   may       261         1     -1         0  unknown  
1  unknown    5   may       151         1     -1         0  unknown  
2  unknown    5   may        76         1     -1         0  unknown  
3  unknown    5   may        92         1     -1         0  unknown  
4  unknown    5   may       198         1     -1         0  unknown  
5  unknown    5   may       139         1     -1         0  unknown  
6  unknown    5   may       217         1     -1         0  unknown  
7  unknown    5   may       380         1     -1         0  unknown  
8  unknown    5   may        50         1     -1         0  unknown  
9  unknown    5   may        55         1     -1         0  unknown

In [36]:
#5 ultimas linhas
df.tail()

age           job   marital  education default  balance housing loan  \
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome  
45206   cellular   17   nov       977         3     -1         0  unknown  
45207   cellular   17   nov       456         2     -1         0  unknown  
45208   cellular   17   nov      1127         5    184         3  success  
45209  telephone   17   nov       508         4     -1         0  unknown  
45210   cellular   17   nov       361         2    188        11    other

In [39]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome'],
      dtype='object')

In [40]:
df.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
dtype: object

In [41]:
#df.marital
df['marital'].value_counts()

married     27214
single      12790
divorced     5207
Name: marital, dtype: int64

In [43]:
df['marital'].value_counts(normalize=True)    
#resultado frequência relativa

married     0.601933
single      0.282896
divorced    0.115171
Name: marital, dtype: float64